---
- name: win_copy
  hosts: all
  become: false
  vars:
    mydest: 'D:\ET0741LabFiles\OpenVAS(student_password)-2024.ova'
    mysrc: '/mnt/ToShare/OpenVAS.ova'
  tasks:
   - name: download file
     ansible.windows.win_copy:
##      src: "/home/administrator/ToPush/NetworkHacking-LTAY24.zip"
#      src: "/mnt/ToShare/OpenVAS(student_password)-2024.ova"
      src: "{{ mysrc }}"
      dest: "{{ mydest }}"



