---
- name: Delete Labtest ZIP
  hosts: all
  become: False
  vars:
    myfolder: 'D:\ET0741LabFiles\NetworkHacking-LTAY24\'
    mydest: 'D:\ET0741LabFiles\NetworkHacking-LTAY24.zip'
  tasks:
   - name: delete file
     win_file:
      path: "{{mydest}}"
      state: absent

   - name: Delete Directory
     ansible.windows.win_file:
        path: "{{myfolder}}"
        state: absent

