- name: Copy directory to Windows PC
  hosts: win
  tasks:
    - name: Copy directory to D: drive
      ansible.windows.win_copy:
        src: /home/administrator/ToPush/ET0709LabTest1
        dest: D:\
        remote_src: yes
