---
- name: remove Proxy
  hosts: all
  gather_facts: true
  tasks:
  - name: Apply proxy for all users
    ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings
      name: ProxySettingsPerUser
      data: 0
      type: dword
      state: absent
  - name: Remove proxy
    win_inet_proxy:
         proxy: 10.32.36.253:3128
