---
- name: Display time on localhost before executing tasks
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Record and display start time on localhost
      ansible.builtin.debug:
        msg: "Start time on localhost: {{ lookup('pipe', 'date') }}"

- name: Ping Windows machines
  hosts: win
  gather_facts: no
  tasks:
    - name: Ping the Windows machines
      ansible.windows.win_ping:

- name: Display time on localhost after executing tasks
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Record and display end time on localhost
      ansible.builtin.debug:
        msg: "End time on localhost: {{ lookup('pipe', 'date') }}"