---
- name: set proxy windows
  hosts: all
  gather_facts: true
  tasks:
  - name: Apply proxy settings for all user
    ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings
      name: ProxySettingsPerUser
      data: 0
      type: dword
      state: present
  - name: Configure to use proxy server
    win_inet_proxy:
      proxy: 10.32.36.253:3128
